### ISSUE TITLE
Change word 'Balance' and 'vested' amount into 'Unlocked and Locked' on wallet

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/threefold_wallet#212]

**Comment by ken-de-moor** [comment]
Need a much clearer description.

First off we already have locked tokens, that's something else than tokens that are unlocked through vesting. Just calling them both locked tokens is going to be super confusing.

Secondly, replace them where? Every single mention of the words balance and vested should be replaced by unlocked and locked? Every variation like "Transfer TFT to the Vesting Wallet in order to vest them" should be changed to "Transfer TFT to the Vesting Wallet in order to lock them" ?

**Comment by ken-de-moor** [comment]
Stale ticket, blocked due to no specs.

**Comment by sasha-astiadi** [comment]
we wont do this anymore
